# Variables y Placeholders

In [2]:
# Importamos la librería TensorFlow
import tensorflow as tf

In [3]:
# Por comodidad abrimos una sesión interactiva 
sess = tf.InteractiveSession()

In [4]:
# Vamos a crear un tensor con valores aleatroios
my_tensor = tf.random_uniform((4,4),minval = 0, maxval = 1)

In [5]:
my_tensor

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

## Variables

In [6]:
my_variable = tf.Variable(initial_value = my_tensor)

In [7]:
print(my_variable)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [8]:
sess.run(my_variable)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable)]]

Hemos obtenido un error al correr la sesión para ver "my_variable" porque no la hemos inicializado.

#### ¡Importante! Siempre deben inicializarse todas las variables globales

In [9]:
# Esta línea es importante y suele olvidarse. 
init = tf.global_variables_initializer()

In [10]:
# Todas las variables se inicializan. 
init.run()

In [11]:
# También nos valdría ejecutar el siguiente comando
sess.run(init)

In [12]:
my_variable.eval()

array([[0.0786792 , 0.68724036, 0.7492435 , 0.66426504],
       [0.42291224, 0.28893125, 0.2424835 , 0.45265377],
       [0.7787442 , 0.59056234, 0.9834558 , 0.34033978],
       [0.4110483 , 0.1609081 , 0.7017517 , 0.74921894]], dtype=float32)

array([[ 0.36661446,  0.38905871,  0.27517724,  0.630615  ],
       [ 0.84615541,  0.90100884,  0.88619483,  0.6631211 ],
       [ 0.42065215,  0.84782505,  0.90248001,  0.84664845],
       [ 0.61524773,  0.08053541,  0.27099919,  0.46581519]], dtype=float32)

In [13]:
sess.run(my_variable)

array([[ 0.36661446,  0.38905871,  0.27517724,  0.630615  ],
       [ 0.84615541,  0.90100884,  0.88619483,  0.6631211 ],
       [ 0.42065215,  0.84782505,  0.90248001,  0.84664845],
       [ 0.61524773,  0.08053541,  0.27099919,  0.46581519]], dtype=float32)

## Placeholders

In [14]:
# Debemos indicar tanto su tamaño como el data type esperado
place_holder = tf.placeholder(tf.float64)

In [15]:
place_holder = tf.placeholder(tf.int32)

In [16]:
# Para la forma de los placeholders se suele indicar como None o # of Features 
# dado que None durante el entrenamiento,se puede llenar el número de muestras
# de nuestros datos, que por lo general es un número no conocido.
place_holder = tf.placeholder(tf.float32,shape=(None,4))